### PR TITLE
Late static binding

### PR DESCRIPTION
**Pull request by GrahamCampbell**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
I guess this other option would be you make that class `final`.

**Comment by soullivaneuh** [comment]
Interesting. Could you please elaborate the difference?

**Comment by soullivaneuh** [comment]
> I guess this other option would be you make that class final.

Yep. :+1:

**Comment by soullivaneuh** [comment]
> Interesting. Could you please elaborate the difference?

Ping! :-)

**Comment by soullivaneuh** [comment]
@GrahamCampbell: If I understand well the documentation, this is interesting for inheritance and maybe performance. Am I right?

**Pull request merged**
